Import('env os')
env["rusting"] = env.Program(os.path.join(".", "rusting"), ["clkinputman.cpp", "clkinputtrigger.cpp", "clkkeybind.cpp", "clkterminator.cpp", "clktex.cpp", "clkwin.cpp", "clkviewport.cpp", "clkmenutrig.cpp", "clkmbuttonbind.cpp", "clkrand.cpp", "loopingbg.cpp", "clktiming.cpp", "messaging.cpp", "clksheet.cpp",
"main.cpp"])
