Import('env os')
env["rusting"] = env.Program(os.path.join(".", "rusting"), ["clkinputman.cpp", "clkinputtrigger.cpp", "clkkeybind.cpp", "clkterminator.cpp", "clktex.cpp", "clkwin.cpp", "grid.cpp", "monster.cpp", "tile.cpp", "clkviewport.cpp", "messaging.cpp", "clkmenutrig.cpp", "clkmbuttonbind.cpp", "clf1.cpp", "gridman.cpp", "protomonster.cpp", "clkrand.cpp", "feature.cpp", "door.cpp", "loopingbg.cpp", "clktiming.cpp", "sdarray.cpp", "navmap.cpp",
"main.cpp"])
